import type { Metadata } from "next";
import { Crimson_Text, DM_Sans, Roboto_Mono } from "next/font/google";
import { Header } from '@/layouts/header/Header';
import { Footer } from '@/layouts/footer/Footer';
import "./globals.css";

const crimsonText = Crimson_Text({
  weight: ["400"],
  variable: "--font-crimson-text",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  weight: ["400", "500", "700"],
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  weight: ["400"],
  variable: "--font-roboto-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${crimsonText.variable} ${dmSans.variable} ${robotoMono.variable}`}>
        <div className="container">
          <Header />
          <main style={{ height: '100vh' }}>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
