import type { Metadata } from "next";
import { Crimson_Text, DM_Sans, Roboto_Mono } from "next/font/google";
import { Header } from '@/layouts/header/Header';
import { Footer } from '@/layouts/footer/Footer';
import { Up } from '@/components/up/Up';
import "./globals.css";

const crimsonText = Crimson_Text({
  weight: ["400"],
  variable: "--font-crimson-text",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  weight: ["400", "500", "700"],
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  weight: ["400"],
  variable: "--font-roboto-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "A landing page for a product to create",
  description: "Generated by create next app",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="robots" content="index, follow" />
        <meta name="googlebot" content="index, follow" />
        {/* остальные мета-теги... */}
      </head>
      <body className={`${crimsonText.variable} ${dmSans.variable} ${robotoMono.variable}`}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
        <Up />
      </body>
    </html>
  );
}
